#!/usr/bin/dh-exec --with=filter
debian/detect/nvidia-detect			usr/bin/
debian/detect/nvidia-legacy-*.ids		usr/share/nvidia/	[amd64 i386 armhf]
debian/detect/nvidia-tesla-418.ids		usr/share/nvidia/	[amd64]
debian/detect/nvidia-tesla-440.ids		usr/share/nvidia/	[amd64]
debian/detect/nvidia-tesla-450.ids		usr/share/nvidia/	[amd64 arm64]
debian/detect/nvidia-tesla-460.ids		usr/share/nvidia/	[amd64 arm64]
debian/detect/nvidia-tesla-470.ids		usr/share/nvidia/	[amd64 arm64]
debian/detect/nvidia-tesla-535.ids		usr/share/nvidia/	[amd64 arm64]
nvidia.ids					usr/share/nvidia/
nvidia-open.ids					usr/share/nvidia/
